$(function(){
	$('#home_link').click(function(){
		$("#about").slideUp("slow");
		$("#services").slideUp("slow");
		$("#clients").slideUp("slow");
		$("#contact").slideUp("slow");
		/*$("#home_link").addClass("tab");*/
		$("#about_link").removeClass("tab");
		$("#services_link").removeClass("tab");
		$("#clients_link").removeClass("tab");
		$("#contact_link").removeClass("tab");
	});
	$('#about_link').click(function(){
		$("#about").slideDown("slow");
		$("#services").fadeOut("fast");
		$("#clients").fadeOut("fast");
		$("#contact").fadeOut("fast");
		$("#about_link").addClass("tab");
		$("#services_link").removeClass("tab");
		$("#clients_link").removeClass("tab");
		$("#contact_link").removeClass("tab");
		/*$("#home_link").removeClass("tab");*/
	});
	$('#services_link').click(function(){
		$("#services").slideDown("slow");
		$("#about").fadeOut("fast");
		$("#clients").fadeOut("fast");
		$("#contact").fadeOut("fast");
		$("#services_link").addClass("tab");
		$("#about_link").removeClass("tab");
		$("#clients_link").removeClass("tab");
		$("#contact_link").removeClass("tab");
		/*$("#home_link").removeClass("tab");*/
	});
	$('#clients_link').click(function(){
		$("#clients").slideDown("slow");
		$("#about").fadeOut("fast");
		$("#services").fadeOut("fast");
		$("#contact").fadeOut("fast");
		$("#clients_link").addClass("tab");
		$("#about_link").removeClass("tab");
		$("#services_link").removeClass("tab");
		$("#contact_link").removeClass("tab");
		/*$("#home_link").removeClass("tab");*/
	});
	$('#contact_link').click(function(){
		$("#contact").slideDown("slow");
		$("#about").fadeOut("fast");
		$("#clients").fadeOut("fast");
		$("#services").fadeOut("fast");
		$("#contact_link").addClass("tab");
		$("#about_link").removeClass("tab");
		$("#clients_link").removeClass("tab");
		$("#services_link").removeClass("tab");
		/*$("#home_link").removeClass("tab");*/
	});
});